spring.application.name=GCash App
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.check-template-location=true

# Logging
logging.level.root=INFO
